out: main.o Tempo.o Estacionamento.o
	g++ -o out main.o Tempo.o Estacionamento.o
main.o: main.cpp
	g++ -c main.cpp
Tempo.o: Tempo.cpp
	g++ -c Tempo.cpp
Estacionamento.o: Estacionamento.cpp
	g++ -c Estacionamento.cpp
