output: main.o ContaCorrente.o Poupanca.o
	g++ -o output main.o ContaCorrente.o Poupanca.o
	
main.o: main.cpp
	g++ -c main.cpp

ContaCorrete.o: ContaCorrente.h ContaCorrente.cpp
	g++ -c ContaCorrente.cpp

Poupanca.o: Poupanca.h Poupanca.cpp
	g++ -c Poupanca.cpp
